### ISSUE TITLE
[Epic] CLI Stability

### ISSUE THREAD

**Issue by tanema** [Shopify/shopify-app-cli#583]
# Issue summary
Our current installation strategy does not lead to a stable CLI experience. There is issues with changing the shell environment, ruby versions, incompatible shells, incompatible operating systems.

### Currently
We have problems with 
- ruby runtime versions
- shell compatibility 
- availability of non-dev tools like `curl` and `which`
- ability to run on windows terminal

### Implementation
We need a new strategy for installing the CLI that will make it
- [ ] have a stable ruby version and runtime.
- [ ] have a stable installation strategy that will work across all systems
- [ ] Enable having required tools made available easily. possibly through package manager requirements
- [ ] cross platform installations (maybe apt-get, chocolatey, homebrew, nix)

### Notes

This will require the removal of some functionality such as the finalizer that loads our development instance and changes directories for us.

**Comment by mkevinosullivan** [comment]
Mostly complete!
- [x] have a stable ruby version and runtime.  _Upon installation, we generate a shell script or batch file that locks onto the version of ruby available.  Even in a multi-ruby environment, the specific version of ruby used stays the same._
- [x] have a stable installation strategy that will work across all systems.  _System specific, and package based, installation options now available for Debian-based Linux, RPM-based Linux, macOS and Windows._
- [x] Enable having required tools made available easily. possibly through package manager requirements.  _Packages list common prerequisites._
- [x] cross platform installations (maybe apt-get, chocolatey, homebrew, nix)
  - _[x] Debian-based Linux - `apt`, `apt-get`, `gem`_
  - _[x] RPM-based Linux - `yum`, `gem`_
  - _[x] Windows 10 - `gem`, `chocolatey` is WIP_
  - _[x] macOS - `brew`, `gem`_
